### ISSUE TITLE
callback listener never triggers

### ISSUE THREAD

**Issue by geniushkg** [greengrowapps/ggarest#3]
this is my sample code , progress bar never getting dismissed

  progress.setTitle("Loading");
        progress.setMessage("Wait while loading...");
        progress.show();
        Log.d("TAG", "progress loader seen");
        GgaRest.ws().get("http://192.168.1.7/v1/api/departments")
                .onSuccess(depart.class, new OnListResponseListener<depart>() {
                    @Override
                    public void onResponse(int code, List<depart> object, Response fullResponse) {
                        progress.dismiss();
                        Log.d("TAG", "on success response executed");
                        for (depart temp : object) {
                            gridArray.add(new dept(homeIcon, temp.getName()));
                        }
                    }
                })
                .onOther(new OnResponseListener() {

```
                @Override
                public void onResponse(int code, Response fullResponse) {
                    progress.dismiss();
                    Log.d("TAG", "on other response executed");
                    Toast.makeText(getActivity(), "Get failed", Toast.LENGTH_SHORT).show();
                }
            }).execute();
```

**Comment by greengrowapps** [comment]
Can you verify that the url provides response? 
Yo can add a timeout listener:
.onTimeout( ... )

PS: We decided to call onOther if you are not listening onTimeout, will come in the next version

**Comment by geniushkg** [comment]
Yes I did verify the url was responding , it was on localhost , anyways please check the code shared @ https://github.com/geniushkg/Ggarest-sample , toast's not displayed.

Also please check this StackOverflow Question and its Answer , simmilar problem arises if ggarest is added in gradle compile. ->
http://stackoverflow.com/questions/22467127/error-duplicate-files-during-packaging-of-apk

you may close the issue , and if possible provide update in upcoming version

**Comment by greengrowapps** [comment]
The problem probably is that you are getting an exception inside the request. You can listen this adding .onException to your calls. 
But I'm doing now that if you don't listen the exception, onOther will be trigged.

Because the jackson library you are getting this duplicate files error. You can solve it adding this to your build.gradle inside the android section:
packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
    }
I will add this in the readme.

Library 0.6 version will come in a few hours, it's being deployed.

**Comment by geniushkg** [comment]
ok thanks
